name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  auto_route: ^8.1.2
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  domain:
    path: ../domain

  auth:
    path: ../feature/auth
  home_screen:
    path: ../feature/home_screen
  play_field_screen:
    path: ../feature/play_field_screen
  profile_screen:
    path: ../feature/profile_screen
  profile_alert_dialog:
    path: ../feature/profile_alert_dialog
  setting_screen:
    path: ../feature/setting_screen

dev_dependencies:
  flutter_lints: ^3.0.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8