name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - ./resources/icons/
    - ./resources/icons/bottle_skins/
    - ./resources/images/
    - ./resources/images/border_skins/
    - ./resources/images/table_skins/

  fonts:
    - family: Pangram
      fonts:
        - asset: ./resources/fonts/pangram/Pangram-Bold.otf
          weight: 700
        - asset: ./resources/fonts/pangram/Pangram-Medium.otf
          weight: 500
        - asset: ./resources/fonts/pangram/Pangram-Regular.otf
          weight: 400

    - family: Rounds
      fonts:
        - asset: ./resources/fonts/rounds/Rounds.ttf
          weight: 400
